Repository ImagingDataCommons/highdicom, pull requests merged in 2021-09, with the labels that each got.

#100 Add properties to Measurement and QualitativeEvaluation
  src/highdicom/sr/templates.py
  tests/test_sr.py
Labels: enhancement

#107 Content items of special templates lack relationship
  src/highdicom/content.py
  src/highdicom/sr/value_types.py
  tests/test_content.py
Labels: bug

#109 Secondary capture example
  docs/usage.rst
Labels: documentation

#108 Fix code name for embedding medium
  src/highdicom/content.py
  tests/test_content.py
Labels: bug

#110 Correct comment in secondary capture usage example
  docs/usage.rst
Labels: documentation

#111 Fix indentation issues
  src/highdicom/legacy/sop.py
Labels: bug
