Repository ImagingDataCommons/highdicom, pull requests merged in 2021-04, with the labels that each got.

#63 Add missing 'optionals' in parameters of SRs
  src/highdicom/sr/sop.py
Labels: documentation

#64 Add test fixture to enable enforce_valid_values flag in pydicom
  tests/conftest.py
Labels: tests

#43 Implement constructors directly from datasets for reference objects
  src/highdicom/sr/content.py
  tests/test_sr.py
Labels: enhancement

#66 Add fallback for missing ReferringPhysicianName, add qualitative_evaluations to test_sr
  src/highdicom/legacy/sop.py
  src/highdicom/seg/sop.py
  src/highdicom/sr/sop.py
  tests/test_sr.py
Labels: enhancement

#68 Spatial Transformer documentation
  docs/package.rst
  src/highdicom/spatial.py
Labels: documentation
