Repository ImagingDataCommons/highdicom, pull requests merged in 2021-11, with the labels that each got.

#132 Implementation of Key Object Selection Document
  docs/package.rst
  src/highdicom/__init__.py
  src/highdicom/content.py
  src/highdicom/ko/__init__.py
  src/highdicom/ko/content.py
  src/highdicom/ko/sop.py
  src/highdicom/seg/__init__.py
  src/highdicom/sr/sop.py
  src/highdicom/sr/utils.py
  src/highdicom/sr/value_types.py
  tests/test_ko.py
Labels: enhancement

#130 Allow users to specify Content Label and ensure the value is formatted correctly
  src/highdicom/ann/sop.py
  src/highdicom/pm/__init__.py
  src/highdicom/pm/sop.py
  src/highdicom/seg/content.py
  src/highdicom/seg/sop.py
  src/highdicom/valuerep.py
  tests/test_pm.py
  tests/test_seg.py
  tests/test_valuerep.py
Labels: bug, enhancement

#133 Fix compliance issues of KO instances
  src/highdicom/ko/sop.py
  tests/test_ko.py
Labels: bug

#138 Add finding category to sr content
  src/highdicom/sr/templates.py
  tests/test_sr.py
Labels: enhancement

#137 Ensure segment pixel data are properly scaled
  src/highdicom/seg/sop.py
  tests/test_seg.py
Labels: bug

#134 Fix `from_dataset` constructor in `KeyObjectSelectionDocument`
  src/highdicom/ko/sop.py
  tests/test_ko.py
Labels: bug
