Repository ImagingDataCommons/highdicom, pull requests merged in 2023-04, with the labels that each got.

#221 Refactor check for described segments to remove unnecessary copies
  src/highdicom/seg/sop.py
Labels: bug

#215 Implement srread function
  src/highdicom/sr/__init__.py
  src/highdicom/sr/sop.py
  tests/test_sr.py
Labels: enhancement

#208 Seg Array Optimization
  docs/usage.rst
  src/highdicom/seg/sop.py
  tests/test_seg.py
Labels: enhancement

#224 Tweaks Following Segmentation Update
  src/highdicom/seg/sop.py
  tests/test_seg.py
Labels: bug, tests

#223 Handle DicomFileLike
  src/highdicom/io.py
  tests/test_io.py
Labels: bug

#226 Allow LongCodeValue and URNCodeValue, add tests
  src/highdicom/sr/coding.py
  tests/test_sr.py
Labels: bug
