Repository ImagingDataCommons/highdicom, pull requests merged in 2023-06, with the labels that each got.

#239 Fixes to various VRs flagged by tests
  src/highdicom/pm/sop.py
  src/highdicom/pr/content.py
  src/highdicom/seg/sop.py
Labels: bug

#238 Exclude incompatible pydicom 2.4.0 in setup.py
  setup.py
Labels: bug

#237 codespell: config, workflow + typos fixed
  .codespellrc
  .github/workflows/codespell.yml
  docs/usage.rst
  src/highdicom/ann/enum.py
  src/highdicom/frame.py
  src/highdicom/ko/sop.py
  src/highdicom/legacy/sop.py
  src/highdicom/pm/sop.py
  src/highdicom/pr/content.py
  src/highdicom/pr/sop.py
  src/highdicom/seg/sop.py
  src/highdicom/sr/__init__.py
  src/highdicom/sr/sop.py
  src/highdicom/sr/templates.py
  src/highdicom/sr/value_types.py
  src/highdicom/utils.py
  tests/test_ko.py
Labels: documentation

#219 Improve User Guide
  data/test_files/sm_annotations.dcm
  data/test_files/sr_document_with_multiple_groups.dcm
  docs/ann.rst
  docs/coding.rst
  docs/conf.py
  docs/general.rst
  docs/generalsr.rst
  docs/images/tid1500_overview.svg
  docs/index.rst
  docs/iods.rst
  docs/kos.rst
  docs/legacy.rst
  docs/package.rst
  docs/pm.rst
  docs/pr.rst
  docs/quickstart.rst
  docs/sc.rst
  docs/seg.rst
  docs/sr.rst
  docs/tid1500.rst
  docs/tid1500parsing.rst
  docs/usage.rst
  src/highdicom/ann/sop.py
  src/highdicom/seg/sop.py
  src/highdicom/sr/__init__.py
Labels: documentation

#240 Convert plane positions to plane position slide sequence
  src/highdicom/seg/content.py
  tests/test_seg.py
Labels: bug

#236 Remove plane orientation from the shared functional groups in case of Slide coordinate system
  data/test_files/seg_image_sm_control.dcm
  data/test_files/seg_image_sm_dots.dcm
  data/test_files/seg_image_sm_numbers.dcm
  src/highdicom/seg/sop.py
  tests/test_seg.py
Labels: bug

#230 ANN parsing improvements
  docs/ann.rst
  src/highdicom/ann/__init__.py
  src/highdicom/ann/content.py
  src/highdicom/ann/sop.py
  tests/test_ann.py
Labels: enhancement
